//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accaunt
    {
        public int Id { get; set; }
        public string User { get; set; }
        public string login { get; set; }
        public string Passvord { get; set; }
    }
}
